### ISSUE TITLE
Color scheme for the property window?

### ISSUE THREAD

**Issue by aaulia** [catppuccin/solvespace#2]
So I know it's hardcoded, but if we compiled our own Solvespace, what would be the correct color scheme to enter in the property window code?

**Comment by ndsboy** [comment]
I like the idea of providing a .patch file (or replacement code) so everyone interested can compile their own fully themed version. I am not so sure about distributing a compiled version as this leads to a lot of extra work, keeping up to date etc. But I'll look into creating a patch file this or next weekend, as this is required either way.

**Comment by ndsboy** [comment]
I've added the required patch files for the toolbar and property window, and a small documentation on how to apply these patches. I was able to build and test these using podman, however I was not able to cross compile solvespace to windows using this method (even without the patches), so I just hope the patches look alright under windows.

@aaulia can an you please test if the patches and documentation work for you as well, and tell me if something needs fixing or I've missed some colors?

**Comment by aaulia** [comment]
> I've added the required patch files for the toolbar and property window, and a small documentation on how to apply these patches. I was able to build and test these using podman, however I was not able to cross compile solvespace to windows using this method (even without the patches), so I just hope the patches look alright under windows.
> 
> @aaulia can an you please test if the patches and documentation work for you as well, and tell me if something needs fixing or I've missed some colors?

Will test it in the morning. Thank you very much for this.

**Comment by aaulia** [comment]
Hi @ndsboy , just want to give you an update. Yeah it works and rocks. 

![Screenshot from 2023-12-17 15-26-26](https://github.com/catppuccin/solvespace/assets/161797/f5edbd1e-ab04-4a4d-80b7-011f5218a5d6)

👍🏼
